### ISSUE TITLE
SGDQ 2024: Missing entry for The Legend of Zelda: Twilight Princess

### ISSUE THREAD

**Issue by crunchtime-ali** [Aldaviva/GamesDoneQuickCalendarFactory#18]
Hey Ben,

thank you for your work on this repo. I imported it into my Google Calender via https://github.com/Aldaviva/GamesDoneQuickCalendarFactory#:~:text=the%20URL%20to-,https%3A//aldaviva.com/docs/gdq.ics,-Click%20the%20Add

I noticed that the entry for Twilight Princess on Friday is missing (see screenshot).
In the schedule data https://tracker.gamesdonequick.com/tracker/api/v2/events/48/runs/ the run looks like this:

```
    {
      "type": "speedrun",
      "id": 6332,
      "name": "The Legend of Zelda: Twilight Princess",
      "display_name": "The Legend of Zelda: Twilight Princess",
      "twitch_name": "",
      "description": "",
      "category": "Co-op Randomizer",
      "coop": true,
      "onsite": "ONSITE",
      "console": "Wii",
      "release_year": null,
      "runners": [
        {
          "type": "runner",
          "id": 711,
          "name": "gymnast86",
          "stream": "https://www.twitch.tv/gymnast86",
          "twitter": "MrGymnast86",
          "youtube": "",
          "platform": "TWITCH",
          "pronouns": "He/Him"
        },
        {
          "type": "runner",
          "id": 60,
          "name": "spikevegeta",
          "stream": "https://twitch.tv/spikevegeta",
          "twitter": "spikevegeta",
          "youtube": "",
          "platform": "TWITCH",
          "pronouns": ""
        }
      ],
      "hosts": [
        {
          "type": "headset",
          "id": 170,
          "name": "PippyInATopHat",
          "pronouns": ""
        }
      ],
      "commentators": [],
      "starttime": "2024-07-05T11:58:00-05:00",
      "endtime": "2024-07-05T14:58:00-05:00",
      "order": 121,
      "run_time": "2:45:00",
      "setup_time": "0:15:00",
      "anchor_time": null,
      "video_links": []
    },
```

![image](https://github.com/Aldaviva/GamesDoneQuickCalendarFactory/assets/7140800/826d6167-e896-4e87-8db8-2b17e4e1b3aa)

Also, can you tell me how often are the iCal feeds are updated? During the event the schedule is changing all the time.

**Comment by Aldaviva** [comment]
Hi @crunchtime-ali,
- I have a change planned to make the Twilight Princess run appear. I will update you here once it's live.
- The iCal feed is updated by my server every 3 minutes, however Google Calendar often requests updates from my server very infrequently, which is really annoying.

**Comment by Aldaviva** [comment]
The update has been deployed and is live now. I verified that `https://aldaviva.com/docs/gdq.ics` returns the Twilight Princess vevent:
```
BEGIN:VEVENT
DESCRIPTION:Co-op Randomizer — Wii\nRun by gymnast86 and spikevegeta\nHost
 ed by PippyInATopHat
DTEND:20240705T195800Z
DTSTAMP:20240618T103353Z
DTSTART:20240705T165800Z
LOCATION:https://www.twitch.tv/gamesdonequick
SEQUENCE:0
SUMMARY:The Legend of Zelda: Twilight Princess
UID:aldaviva.com/SGDQ2024/The Legend of Zelda: Twilight Princess
END:VEVENT
```

As I mentioned, Google Calendar is very slow to update, so it may take a while for you to observe this change.

**Comment by crunchtime-ali** [comment]
Thank you for the super quick fix @Aldaviva 
It took like two hours for the Google Calendar to reflect the change. I might need to switch to another calendar app.

**Comment by Aldaviva** [comment]
You're welcome! Glad it's working for you now.

Yeah during an event Google Calendar's infrequent updates can make it fall so far behind that my phone notifies me about a run starting just as it's actually ending if they're ahead of schedule.
I'm using the built-in calendar functionality in the [Vivaldi](https://vivaldi.com) browser, which supports web calendars like this one, as well as connecting to a Google Calendar account.

**Comment by Aldaviva** [comment]
@crunchtime-ali You can try the [new Google Calendar native integration](https://calendar.google.com/calendar/u/0?cid=ZThmNDEwMmU3MjFlMmExNDAwZjc4NmExMWU2MjlkZGQ4YTlhOGY5ODRiZjFmMjg4NGI5NmFmYjBhYWM2Zjk0N0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t) that should update faster than the old technique.
